from __future__ import annotations

from importlib import import_module

# Compatibility entrypoint for the legacy ui package.
# Keep concrete forwarding logic in each sibling module; this package
# only centralizes stable exports and lazy-loads them on demand.
_MODULE_EXPORTS = {
    'constants': ['PAGE_INTRO', 'PAGE_WELCOME', 'PAGE_AI_SELECT', 'PAGE_AI_IMPORT', 'PAGE_AI_IMPORT_CONTENT', 'PAGE_DEDUPE_RESULT', 'PAGE_AI_ANALYSIS', 'PAGE_IMPORT_SUCCESS', 'DEFAULT_WINDOW_WIDTH', 'DEFAULT_WINDOW_HEIGHT', 'QT_MAX_WINDOW_SIZE'],
    'styles': ['APP_STYLESHEET', 'rounded_panel_stylesheet'],
    'wizard_base': ['PRODUCT_TITLE', 'DEFAULT_WIZARD_BUTTON_LAYOUT', 'AppWizardBase'],
    'message_box': ['MESSAGE_BOX_BUTTON_MIN_WIDTH', 'MESSAGE_BOX_BUTTON_MIN_HEIGHT', 'style_message_box_buttons', 'show_message_box'],
    'table_copy': ['table_cell_text', 'selected_table_as_tsv', 'copy_table_as_tsv', 'CopyableTableWidget'],
    'api_config_dialog': ['ApiConfigDialog'],
    'program_settings_dialog': ['SECTION_GENERAL', 'SECTION_IMPORT', 'SECTION_EXPORT', 'ProgramSettingsDialog'],
    'question_edit_dialog': ['LevelPathPartLineEdit', 'QuestionEditDialog'],
    'import_cost_history_dialog': ['ImportCostHistoryDialog'],
    'compare_highlight': ['compare_highlight_model_styles'],
    'import_page_common': ['LEVEL_PATH_RE', 'LEVEL_PATH_EDIT_RE', 'style_dialog_button', 'style_busy_progress', 'sanitize_filename', 'unique_child_dir', 'rename_project', 'extract_paths_from_drop_event', 'merge_paths_text', 'is_valid_level_path', 'LevelPathItemDelegate', 'PreserveCellBackgroundDelegate'],
    'import_select_reminder': ['inspect_docx_content', 'make_import_check_item', 'populate_import_reminder_columns'],
    'import_select_session': ['safe_mtime_ns', 'word_lock_path', 'build_opened_doc_session', 'poll_opened_doc_sessions', 'select_first_changed_row'],
    'import_question_ref_detail': ['question_ref_row_background', 'question_ref_detail_headers', 'question_ref_detail_model_specs', 'question_ref_detail_model_values', 'question_ref_number_order', 'question_type_options', 'question_type_from_candidates', 'question_type_conflicts', 'build_question_ref_detail_rows', 'build_manual_type_combo', 'populate_question_ref_detail_table'],
    'import_ref_session': ['QuestionRefRuntimeState'],
    'import_content_detail': ['format_json_cell', 'question_ref_total_count', 'question_content_active_model_specs', 'effective_content_question_workers', 'question_content_payload_model_specs', 'question_content_model_signature', 'question_content_detail_headers', 'has_question_content_payload', 'sec_int', 'record_round_sec', 'format_round_secs', 'content_detail_width_signature', 'calculate_content_detail_column_widths', 'apply_content_detail_column_widths', 'set_content_detail_item', 'compare_row_brush', 'apply_compare_row_background', 'clear_compare_payload_background', 'highlight_sig_text', 'apply_partial_pass_highlight', 'build_compare_verdict'],
    'import_progress': ['extract_question_ref_source_name', 'parse_content_progress_message'],
    'import_workers': ['AiQuestionRefWorker', 'AiImportContentWorker'],
    'import_db_service': ['commit_draft_questions_to_db'],
    'import_costs': ['begin_app_import_cost_capture', 'capture_import_cost_before', 'capture_import_cost_before_async', 'wait_import_cost_before_capture', 'freeze_import_cost_result'],
    'welcome_menu': ['WelcomeMenuBundle', 'build_welcome_menu_bar'],
    'welcome_page_actions': ['TableImportResult', 'open_api_config', 'open_program_settings', 'import_from_table_file'],
    'welcome_import': ['effective_import_source_dir', 'backup_import_source_files', 'build_doc_hash_index', 'file_sha256', 'next_doc_backup_path', 'open_import_flow_windows', 'open_import_flow_states', 'show_import_flow_window'],
    'welcome_export': ['sanitize_export_name', 'display_export_level_name', 'default_export_dir', 'db_record_to_question', 'format_db_options', 'format_db_answer', 'format_choice_mapping', 'digit_to_circled', 'export_current_level_to_markdown', 'export_current_level_to_pdf', 'export_db_records_to_xlsx'],
    'welcome_export_actions': ['selected_tree_level_path', 'export_current_level_markdown', 'export_current_level_pdf', 'export_current_level_xlsx', 'export_db_table_xlsx'],
    'welcome_question_actions': ['selected_tree_level_path_for_create', 'build_new_question_record', 'add_question_manually', 'QuestionEditResult', 'edit_question_record'],
    'welcome_table': ['populate_questions_table', 'populate_db_records_table', 'build_question_row_values', 'build_db_row_values', 'populate_row_by_values', 'QtAlign', 'format_stem_with_sequence', 'format_table_analysis', 'set_table_item'],
    'welcome_table_view': ['load_column_visibility', 'save_column_visibility', 'set_column_visible', 'schedule_table_row_resize', 'apply_table_row_resize', 'apply_table_row_resize_followup', 'refresh_table_layout_after_column_change', 'rebalance_visible_columns', 'load_table_font_point_size', 'apply_table_font_size', 'adjust_table_font_size', 'persist_table_font_point_size'],
    'welcome_tree': ['delete_action_text', 'delete_scope_text', 'parse_level_parts', 'display_level_parts', 'tree_level_key_for_path', 'load_questions_for_tree_level', 'format_level_label', 'expand_item_ancestors', 'collect_expanded_level_prefixes', 'build_level_tree', 'to_chinese_number'],
    'welcome_tree_actions': ['refresh_level_tree', 'handle_level_selection_changed', 'show_folder_tree_context_menu', 'sync_expanded_level_prefixes_from_tree', 'delete_level_subtree'],
    "pages": ['IntroPage', 'WelcomePage', 'AiSelectFilesPage', 'AiImportPage', 'AiImportContentPage', 'DedupeResultPage', 'AiAnalysisPage', 'ImportSuccessPage'],
}

_OMITTED_EXPORTS = ('BUTTON_MIN_HEIGHT', 'BUTTON_MIN_WIDTH')

_EXPORT_TO_MODULE = {
    name: module_name
    for module_name, names in _MODULE_EXPORTS.items()
    for name in names
}

__all__ = [
    'PAGE_INTRO',
    'PAGE_WELCOME',
    'PAGE_AI_SELECT',
    'PAGE_AI_IMPORT',
    'PAGE_AI_IMPORT_CONTENT',
    'PAGE_DEDUPE_RESULT',
    'PAGE_AI_ANALYSIS',
    'PAGE_IMPORT_SUCCESS',
    'DEFAULT_WINDOW_WIDTH',
    'DEFAULT_WINDOW_HEIGHT',
    'QT_MAX_WINDOW_SIZE',
    'APP_STYLESHEET',
    'rounded_panel_stylesheet',
    'PRODUCT_TITLE',
    'DEFAULT_WIZARD_BUTTON_LAYOUT',
    'AppWizardBase',
    'MESSAGE_BOX_BUTTON_MIN_WIDTH',
    'MESSAGE_BOX_BUTTON_MIN_HEIGHT',
    'style_message_box_buttons',
    'show_message_box',
    'table_cell_text',
    'selected_table_as_tsv',
    'copy_table_as_tsv',
    'CopyableTableWidget',
    'ApiConfigDialog',
    'SECTION_GENERAL',
    'SECTION_IMPORT',
    'SECTION_EXPORT',
    'ProgramSettingsDialog',
    'LevelPathPartLineEdit',
    'QuestionEditDialog',
    'ImportCostHistoryDialog',
    'compare_highlight_model_styles',
    'LEVEL_PATH_RE',
    'LEVEL_PATH_EDIT_RE',
    'style_dialog_button',
    'style_busy_progress',
    'sanitize_filename',
    'unique_child_dir',
    'rename_project',
    'extract_paths_from_drop_event',
    'merge_paths_text',
    'is_valid_level_path',
    'LevelPathItemDelegate',
    'PreserveCellBackgroundDelegate',
    'inspect_docx_content',
    'make_import_check_item',
    'populate_import_reminder_columns',
    'safe_mtime_ns',
    'word_lock_path',
    'build_opened_doc_session',
    'poll_opened_doc_sessions',
    'select_first_changed_row',
    'question_ref_row_background',
    'question_ref_detail_headers',
    'question_ref_detail_model_specs',
    'question_ref_detail_model_values',
    'question_ref_number_order',
    'question_type_options',
    'question_type_from_candidates',
    'question_type_conflicts',
    'build_question_ref_detail_rows',
    'build_manual_type_combo',
    'populate_question_ref_detail_table',
    'QuestionRefRuntimeState',
    'format_json_cell',
    'question_ref_total_count',
    'question_content_active_model_specs',
    'effective_content_question_workers',
    'question_content_payload_model_specs',
    'question_content_model_signature',
    'question_content_detail_headers',
    'has_question_content_payload',
    'sec_int',
    'record_round_sec',
    'format_round_secs',
    'content_detail_width_signature',
    'calculate_content_detail_column_widths',
    'apply_content_detail_column_widths',
    'set_content_detail_item',
    'compare_row_brush',
    'apply_compare_row_background',
    'clear_compare_payload_background',
    'highlight_sig_text',
    'apply_partial_pass_highlight',
    'build_compare_verdict',
    'extract_question_ref_source_name',
    'parse_content_progress_message',
    'AiQuestionRefWorker',
    'AiImportContentWorker',
    'commit_draft_questions_to_db',
    'begin_app_import_cost_capture',
    'capture_import_cost_before',
    'capture_import_cost_before_async',
    'wait_import_cost_before_capture',
    'freeze_import_cost_result',
    'WelcomeMenuBundle',
    'build_welcome_menu_bar',
    'TableImportResult',
    'open_api_config',
    'open_program_settings',
    'import_from_table_file',
    'effective_import_source_dir',
    'backup_import_source_files',
    'build_doc_hash_index',
    'file_sha256',
    'next_doc_backup_path',
    'open_import_flow_windows',
    'open_import_flow_states',
    'show_import_flow_window',
    'sanitize_export_name',
    'display_export_level_name',
    'default_export_dir',
    'db_record_to_question',
    'format_db_options',
    'format_db_answer',
    'format_choice_mapping',
    'digit_to_circled',
    'export_current_level_to_markdown',
    'export_current_level_to_pdf',
    'export_db_records_to_xlsx',
    'selected_tree_level_path',
    'export_current_level_markdown',
    'export_current_level_pdf',
    'export_current_level_xlsx',
    'export_db_table_xlsx',
    'selected_tree_level_path_for_create',
    'build_new_question_record',
    'add_question_manually',
    'QuestionEditResult',
    'edit_question_record',
    'populate_questions_table',
    'populate_db_records_table',
    'build_question_row_values',
    'build_db_row_values',
    'populate_row_by_values',
    'QtAlign',
    'format_stem_with_sequence',
    'format_table_analysis',
    'set_table_item',
    'load_column_visibility',
    'save_column_visibility',
    'set_column_visible',
    'schedule_table_row_resize',
    'apply_table_row_resize',
    'apply_table_row_resize_followup',
    'refresh_table_layout_after_column_change',
    'rebalance_visible_columns',
    'load_table_font_point_size',
    'apply_table_font_size',
    'adjust_table_font_size',
    'persist_table_font_point_size',
    'delete_action_text',
    'delete_scope_text',
    'parse_level_parts',
    'display_level_parts',
    'tree_level_key_for_path',
    'load_questions_for_tree_level',
    'format_level_label',
    'expand_item_ancestors',
    'collect_expanded_level_prefixes',
    'build_level_tree',
    'to_chinese_number',
    'refresh_level_tree',
    'handle_level_selection_changed',
    'show_folder_tree_context_menu',
    'sync_expanded_level_prefixes_from_tree',
    'delete_level_subtree',
    'IntroPage',
    'WelcomePage',
    'AiSelectFilesPage',
    'AiImportPage',
    'AiImportContentPage',
    'DedupeResultPage',
    'AiAnalysisPage',
    'ImportSuccessPage',
]


def __getattr__(name: str):
    module_name = _EXPORT_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
